<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;

class RFIController extends Controller
{
    public function index(): JsonResponse
    {
        return response()->json([
            'data' => [
                [
                    'id' => 1,
                    'number' => 'RFI-001',
                    'subject' => 'Structural Steel Connection Detail',
                    'description' => 'Clarification required on beam-to-column connection at Level 3 Gridline C-D. Current drawings show two conflicting details — Figure 3.2 shows a fin plate connection while Detail Sheet S-104 shows a full depth end plate. Please confirm which connection type is intended.',
                    'status' => 'Open',
                    'priority' => 'High',
                    'project' => 'Battersea Phase 2',
                    'trade' => 'Structural',
                    'sentTo' => 'Buro Happold',
                    'sentDate' => '28 Apr 2026',
                    'dueDate' => '05 May 2026',
                    'assignee' => 'Tom Mitchell',
                    'daysOpen' => 9,
                    'costImpact' => '£12,500',
                    'attachments' => 3,
                    'response' => '',
                    'responseDate' => '',
                ],
                [
                    'id' => 2,
                    'number' => 'RFI-002',
                    'subject' => 'Foundation Reinforcement Spacing',
                    'description' => 'Query on rebar spacing in pad foundations per latest revision of structural drawings. Revision 4 shows 200mm centres but the bar schedule specifies 175mm. Clarification needed before concrete pour scheduled for Monday.',
                    'status' => 'Closed',
                    'priority' => 'Medium',
                    'project' => 'Manchester Metro Hub',
                    'trade' => 'Structural',
                    'sentTo' => 'Arup & Partners',
                    'sentDate' => '25 Apr 2026',
                    'dueDate' => '02 May 2026',
                    'assignee' => 'Sarah Collins',
                    'daysOpen' => 5,
                    'costImpact' => '£0',
                    'attachments' => 2,
                    'response' => 'Use 175mm centres as per bar schedule. Drawing revision 5 to be issued reflecting this change.',
                    'responseDate' => '30 Apr 2026',
                ],
                [
                    'id' => 3,
                    'number' => 'RFI-003',
                    'subject' => 'External Wall U-Value Compliance',
                    'description' => 'Confirm that proposed cladding system meets Part L 2026 U-value requirements. Calculations show 0.17 W/m2K which exceeds the 0.18 threshold. Please advise if an alternative insulation thickness is required.',
                    'status' => 'Closed',
                    'priority' => 'High',
                    'project' => 'Leeds Green Park',
                    'trade' => 'Cladding',
                    'sentTo' => 'Mott MacDonald',
                    'sentDate' => '15 Apr 2026',
                    'dueDate' => '22 Apr 2026',
                    'assignee' => 'Priya Sharma',
                    'daysOpen' => 4,
                    'costImpact' => '£45,000',
                    'attachments' => 5,
                    'response' => 'Approved as designed. U-value of 0.17 W/m2K exceeds requirement. No changes to insulation specification needed.',
                    'responseDate' => '19 Apr 2026',
                ],
                [
                    'id' => 4,
                    'number' => 'RFI-004',
                    'subject' => 'Drainage Layout Conflict',
                    'description' => 'Foul drainage route conflicts with proposed piling layout at Gridline 5. The 300mm pipe runs directly through pile cap P12. Need alternative routing before piling works commence.',
                    'status' => 'Open',
                    'priority' => 'High',
                    'project' => 'Bristol Harbour Bridge',
                    'trade' => 'M&E',
                    'sentTo' => 'Arup & Partners',
                    'sentDate' => '01 May 2026',
                    'dueDate' => '08 May 2026',
                    'assignee' => 'James Whitfield',
                    'daysOpen' => 6,
                    'costImpact' => '£8,200',
                    'attachments' => 4,
                    'response' => '',
                    'responseDate' => '',
                ],
                [
                    'id' => 5,
                    'number' => 'RFI-005',
                    'subject' => 'HVAC Duct Routing Through Beam Web',
                    'description' => 'Request to approve 400mm diameter duct penetration through steel beam web at Level 2. Structural engineer needs to confirm if stiffener plates are required around the penetration.',
                    'status' => 'Closed',
                    'priority' => 'Medium',
                    'project' => 'Newcastle Innovation Centre',
                    'trade' => 'M&E',
                    'sentTo' => 'Buro Happold',
                    'sentDate' => '20 Apr 2026',
                    'dueDate' => '27 Apr 2026',
                    'assignee' => 'Alex Thornton',
                    'daysOpen' => 6,
                    'costImpact' => '£3,800',
                    'attachments' => 2,
                    'response' => 'Approved with condition: 10mm thick stiffener plates required on all four sides of penetration. Detail to be issued by M&E coordinator.',
                    'responseDate' => '26 Apr 2026',
                ],
                [
                    'id' => 6,
                    'number' => 'RFI-006',
                    'subject' => 'Temporary Works Design for Facade',
                    'description' => 'Need temporary works design for edge protection during cladding installation at height. Current design shows standard guardrail but the cantilever edge requires a specialized solution.',
                    'status' => 'Open',
                    'priority' => 'Medium',
                    'project' => 'Birmingham Central Plaza',
                    'trade' => 'Scaffolding',
                    'sentTo' => 'Mott MacDonald',
                    'sentDate' => '03 May 2026',
                    'dueDate' => '10 May 2026',
                    'assignee' => 'Rachel Okafor',
                    'daysOpen' => 4,
                    'costImpact' => 'TBC',
                    'attachments' => 1,
                    'response' => '',
                    'responseDate' => '',
                ],
            ],
        ]);
    }
}
